language: generic
os: linux

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - ROSWELL_VERSION=20.06.14.107
    - ROSWELL_URL="https://raw.githubusercontent.com/roswell/roswell/v$ROSWELL_VERSION/scripts/install-for-ci.sh"

  jobs:
    # - LISP=abcl
    # - LISP=allegro
    # - LISP=ccl
    # - LISP=clisp
    # - LISP=cmucl
    # - LISP=ecl
    - LISP=sbcl-bin

jobs:
  allow_failures:
    - env: LISP=abcl
    - env: LISP=allegro
    - env: LISP=ccl
    - env: LISP=clisp
    - env: LISP=cmucl
    - env: LISP=ecl

install:
  - curl -L $ROSWELL_URL | sh

script:
  - make test-ros
